'use client'

import { useState, useEffect, useCallback } from 'react'
import Image from 'next/image'

interface FlowMeterSlide {
  id: string
  name: string
  principle: string
  description: string
  color: string
  applications: string[]
}

const slides: FlowMeterSlide[] = [
  {
    id: 'ultrasonic',
    name: 'Ultrasonic Flow Meter',
    principle: 'Transit-Time Measurement',
    description:
      'Measures flow velocity by calculating the difference in transit time of ultrasonic pulses sent upstream and downstream through the fluid.',
    color: 'from-cyan-500/80 to-blue-600/80',
    applications: ['Water distribution', 'HVAC systems', 'Chemical processing'],
  },
  {
    id: 'electromagnetic',
    name: 'Electromagnetic Flow Meter',
    principle: "Faraday's Law of Induction",
    description:
      'Uses a magnetic field and electrodes to measure the voltage generated by conductive fluid flowing through the pipe.',
    color: 'from-purple-500/80 to-fuchsia-600/80',
    applications: ['Wastewater', 'Pulp & paper', 'Food & beverage'],
  },
  {
    id: 'coriolis',
    name: 'Coriolis Mass Flow Meter',
    principle: 'Coriolis Effect',
    description:
      'Vibrating tubes twist proportionally to mass flow rate, providing direct mass flow and density measurements.',
    color: 'from-emerald-500/80 to-teal-600/80',
    applications: ['Oil & gas custody transfer', 'Pharmaceuticals', 'Chemical batching'],
  },
  {
    id: 'vortex',
    name: 'Vortex Flow Meter',
    principle: 'Von Karman Vortex Street',
    description:
      'A bluff body creates alternating vortices whose frequency is proportional to flow velocity.',
    color: 'from-orange-500/80 to-amber-600/80',
    applications: ['Steam measurement', 'Compressed air', 'Natural gas'],
  },
  {
    id: 'turbine',
    name: 'Turbine Flow Meter',
    principle: 'Rotational Velocity',
    description:
      'Fluid flow spins a rotor whose rotational speed is measured by a magnetic pickup, proportional to volumetric flow.',
    color: 'from-red-500/80 to-rose-600/80',
    applications: ['Fuel metering', 'Water treatment', 'Hydraulic systems'],
  },
  {
    id: 'differential-pressure',
    name: 'Differential Pressure Flow Meter',
    principle: "Bernoulli's Principle",
    description:
      'An orifice plate creates a pressure drop proportional to flow rate squared, measured by upstream and downstream pressure taps.',
    color: 'from-yellow-500/80 to-amber-600/80',
    applications: ['Power plants', 'Refineries', 'Gas pipelines'],
  },
]

export default function FlowMeterSlideshow() {
  const [current, setCurrent] = useState(0)
  const [isTransitioning, setIsTransitioning] = useState(false)
  const [isPaused, setIsPaused] = useState(false)

  const goToSlide = useCallback(
    (index: number) => {
      if (isTransitioning || index === current) return
      setIsTransitioning(true)
      setCurrent(index)
      setTimeout(() => setIsTransitioning(false), 600)
    },
    [isTransitioning, current]
  )

  const nextSlide = useCallback(() => {
    goToSlide((current + 1) % slides.length)
  }, [current, goToSlide])

  const prevSlide = useCallback(() => {
    goToSlide((current - 1 + slides.length) % slides.length)
  }, [current, goToSlide])

  // Auto-advance every 6 seconds
  useEffect(() => {
    if (isPaused) return
    const timer = setInterval(nextSlide, 6000)
    return () => clearInterval(timer)
  }, [nextSlide, isPaused])

  const slide = slides[current]

  return (
    <div
      className="relative overflow-hidden rounded-2xl border border-white/20 bg-white/5 shadow-2xl backdrop-blur-md"
      onMouseEnter={() => setIsPaused(true)}
      onMouseLeave={() => setIsPaused(false)}
    >
      {/* Image Container */}
      <div className="relative aspect-[16/10] w-full overflow-hidden">
        {slides.map((s, i) => (
          <div
            key={s.id}
            className={`absolute inset-0 transition-all duration-600 ease-in-out ${
              i === current
                ? 'scale-100 opacity-100'
                : i < current
                  ? '-translate-x-full scale-95 opacity-0'
                  : 'translate-x-full scale-95 opacity-0'
            }`}
          >
            <Image
              src={`/images/infographics/${s.id}.jpg`}
              alt={s.name}
              fill
              className="object-cover"
              priority={i === 0}
              sizes="(max-width: 768px) 100vw, 50vw"
            />
          </div>
        ))}

        {/* Gradient overlay for text readability */}
        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />

        {/* Navigation arrows */}
        <button
          onClick={prevSlide}
          className="absolute left-3 top-1/2 z-10 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full bg-white/20 text-white backdrop-blur-sm transition-all hover:bg-white/40"
          aria-label="Previous slide"
        >
          <span className="material-icons text-lg">chevron_left</span>
        </button>
        <button
          onClick={nextSlide}
          className="absolute right-3 top-1/2 z-10 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full bg-white/20 text-white backdrop-blur-sm transition-all hover:bg-white/40"
          aria-label="Next slide"
        >
          <span className="material-icons text-lg">chevron_right</span>
        </button>

        {/* Slide info overlay */}
        <div className="absolute bottom-0 left-0 right-0 z-10 p-5">
          <div
            className={`mb-2 inline-flex items-center rounded-full bg-gradient-to-r ${slide.color} px-3 py-1 text-xs font-semibold text-white backdrop-blur-sm`}
          >
            <span className="material-icons mr-1 text-sm">science</span>
            {slide.principle}
          </div>

          <h3 className="mb-1 text-xl font-bold text-white">{slide.name}</h3>
          <p className="mb-3 text-sm leading-relaxed text-white/80">
            {slide.description}
          </p>

          {/* Applications tags */}
          <div className="flex flex-wrap gap-1.5">
            {slide.applications.map((app) => (
              <span
                key={app}
                className="rounded-md bg-white/15 px-2 py-0.5 text-[10px] font-medium text-white/90 backdrop-blur-sm"
              >
                {app}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Slide indicators */}
      <div className="flex items-center justify-center gap-2 bg-black/30 px-4 py-3 backdrop-blur-sm">
        {slides.map((s, i) => (
          <button
            key={s.id}
            onClick={() => goToSlide(i)}
            className={`group relative h-1.5 rounded-full transition-all duration-300 ${
              i === current ? 'w-8 bg-white' : 'w-1.5 bg-white/40 hover:bg-white/60'
            }`}
            aria-label={`Go to ${s.name}`}
          >
            {/* Tooltip */}
            <span className="pointer-events-none absolute -top-8 left-1/2 -translate-x-1/2 whitespace-nowrap rounded bg-black/80 px-2 py-1 text-[10px] text-white opacity-0 transition-opacity group-hover:opacity-100">
              {s.name}
            </span>
          </button>
        ))}
      </div>

      {/* Auto-play progress bar */}
      {!isPaused && (
        <div className="absolute left-0 right-0 top-0 h-0.5">
          <div
            className="h-full bg-white/60"
            style={{
              animation: 'slideProgress 6s linear infinite',
            }}
          />
        </div>
      )}

      <style jsx>{`
        @keyframes slideProgress {
          from {
            width: 0%;
          }
          to {
            width: 100%;
          }
        }
      `}</style>
    </div>
  )
}
