// Resend Email Service
// Wrapper for Resend API with attachment support

import { Resend } from 'resend'

// Lazy initialization to avoid build-time errors
let resendInstance: Resend | null = null

function getResendClient(): Resend | null {
  if (!process.env.RESEND_API_KEY) {
    return null
  }
  if (!resendInstance) {
    resendInstance = new Resend(process.env.RESEND_API_KEY)
  }
  return resendInstance
}

export interface EmailAttachment {
  filename: string
  content: Buffer | Uint8Array
  contentType?: string
}

export interface SendEmailOptions {
  to: string | string[]
  subject: string
  html: string
  text?: string
  attachments?: EmailAttachment[]
  replyTo?: string
}

export interface SendEmailResult {
  success: boolean
  id?: string
  error?: string
}

// Send email using Resend API
export async function sendEmail(options: SendEmailOptions): Promise<SendEmailResult> {
  const fromAddress = process.env.EMAIL_FROM || 'FlowNexus Reports <reports@flownexus.com>'

  // Get Resend client (lazy initialization)
  const resend = getResendClient()

  // Check if Resend is configured
  if (!resend) {
    console.warn('RESEND_API_KEY not configured, skipping email send')
    return {
      success: false,
      error: 'Email service not configured (missing RESEND_API_KEY)',
    }
  }

  try {
    const recipients = Array.isArray(options.to) ? options.to : [options.to]

    // Filter out empty emails
    const validRecipients = recipients.filter(email => email && email.trim().length > 0)

    if (validRecipients.length === 0) {
      return {
        success: false,
        error: 'No valid recipients provided',
      }
    }

    const attachments = options.attachments?.map(att => ({
      filename: att.filename,
      content: att.content instanceof Buffer ? att.content : Buffer.from(att.content),
    }))

    const { data, error } = await resend.emails.send({
      from: fromAddress,
      to: validRecipients,
      subject: options.subject,
      html: options.html,
      text: options.text,
      replyTo: options.replyTo,
      attachments,
    })

    if (error) {
      console.error('Resend API error:', error)
      return {
        success: false,
        error: error.message || 'Failed to send email',
      }
    }

    console.log(`Email sent successfully: ${data?.id}`)
    return {
      success: true,
      id: data?.id,
    }
  } catch (err) {
    console.error('Email send error:', err)
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unknown email error',
    }
  }
}

// Send daily report email with PDF attachment
export async function sendDailyReportEmail(
  recipients: string[],
  companyName: string,
  reportDate: string,
  summaryHtml: string,
  pdfBuffer: Uint8Array | Buffer
): Promise<SendEmailResult> {
  const subject = `FlowNexus Daily Report - ${companyName} - ${reportDate}`

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      </head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #1f2937; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #1e3a5f 0%, #0e7490 100%); padding: 24px; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">FlowNexus SCADA</h1>
          <p style="color: rgba(255,255,255,0.8); margin: 8px 0 0 0; font-size: 14px;">Daily Flow Monitoring Report</p>
        </div>

        <div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-top: none;">
          <p style="margin: 0 0 16px 0;">Hello,</p>
          <p style="margin: 0 0 16px 0;">Please find attached the daily flow monitoring report for <strong>${companyName}</strong> dated <strong>${reportDate}</strong>.</p>

          ${summaryHtml}

          <p style="margin: 24px 0 0 0; font-size: 14px; color: #64748b;">
            This is an automated report. For questions or issues, please contact your system administrator.
          </p>
        </div>

        <div style="background: #1e293b; padding: 16px 24px; border-radius: 0 0 12px 12px; text-align: center;">
          <p style="color: rgba(255,255,255,0.6); margin: 0; font-size: 12px;">
            Generated by FlowNexus SCADA | Version 3.3
          </p>
        </div>
      </body>
    </html>
  `

  const text = `
FlowNexus Daily Report - ${companyName} - ${reportDate}

Please find attached the daily flow monitoring report.

This is an automated report. For questions or issues, please contact your system administrator.
  `.trim()

  return sendEmail({
    to: recipients,
    subject,
    html,
    text,
    attachments: [
      {
        filename: `FlowNexus-Daily-Report-${reportDate}.pdf`,
        content: pdfBuffer instanceof Buffer ? pdfBuffer : Buffer.from(pdfBuffer),
        contentType: 'application/pdf',
      },
    ],
  })
}
