-- Migration: Add zero_flow alert type
-- Date: 2026-01-24
-- Description: Adds zero_flow to alert_type and rule_type constraints

-- Drop and recreate the alert_type constraint on alerts table
ALTER TABLE alerts DROP CONSTRAINT IF EXISTS alerts_alert_type_check;
ALTER TABLE alerts ADD CONSTRAINT alerts_alert_type_check
  CHECK (alert_type IN ('high_flow', 'low_flow', 'no_data', 'device_offline', 'battery_low', 'zero_flow', 'custom'));

-- Drop and recreate the rule_type constraint on alert_rules table
ALTER TABLE alert_rules DROP CONSTRAINT IF EXISTS alert_rules_rule_type_check;
ALTER TABLE alert_rules ADD CONSTRAINT alert_rules_rule_type_check
  CHECK (rule_type IN ('high_flow', 'low_flow', 'no_data', 'device_offline', 'battery_low', 'zero_flow'));

-- Add a comment documenting the change
COMMENT ON TABLE alerts IS 'Stores alerts generated by the system. Includes zero_flow alert type for detecting zero flow conditions.';
COMMENT ON TABLE alert_rules IS 'Stores alert rules configuration for devices. Includes zero_flow rule type for detecting zero flow conditions.';
